### ISSUE TITLE
Suggestion: resolve same country in other language if nothing else matches

### ISSUE THREAD

**Issue by L3444** [Avansai/resolve-accept-language#12]
Hello, thank you for this library. I just have a suggestion for an additional (maybe optional) MatchType:

When all other MatchTypes have found nothing and the current implementation would return the defaultLocale, attempt the following match:

- Only look at the country codes. What is the highest quality country code that is also a country code in one of the supported locales?
- Return the first supported locale with that country code

This MatchType would basically be the same as the already implemented "relatedLocaleBased", just for countries instead of languages. The idea behind it is that if no language matches, it would be better to at least stay in the country you're accepting instead of using the default locale which is not in your language and probably also not your country.

Example:
- the user only accepts "af-ZA"
- the default locale is "en-US"
- none of the supported locales support the language "af", but one of those locales is "en-ZA"

With this new MatchType, the user would receive "en-ZA", which is a better match for them than the default "en-US" because at least the country would still match their preference.

**Comment by nbouvrette** [comment]
Thank you.

What if `en-ZA` is not one of those locale but `zu-ZA` (Zulu) is instead. And the person only speaks `af-ZA` (African) and English (they don't know Zulu). If we pick `zu-ZA` they won't be able to understand the page's content. But if we would have defaulted to English then this would not be a problem.

Of course this is very speculative because most likely the person would have the correct setting in their OS/Browser and we would be able to match them correctly.

I did consider doing country fallback in the original implementation but I think my thought at that point was that the country didn't make much of a different if you cannot speak the language.

Thinking more about this now, I can see some benefits doing country fallback. Let's say we use `zu-ZA` as default instead of `en-US` - most browsers offer page translations - and if this is done then the page's translation would be closer to an `af-ZA` (quality might vary depending on language pairs). But the main difference is that currency and data formats would be from South Africa instead of from the US.

But one thing to also consider if that often the quality of the default language is better than the translations... so there is a benefit to this as well if the primary goal it to make sure that the end user understand the content without adding a layer of translation + machine translation on top which could definitely lower the quality.

I'll think about it a bit more but like you suggested, maybe adding this as an optional match since it's a bit more speculative than the other matches.

**Comment by L3444** [comment]
Hi, just responding to that first point:

>What if en-ZA is not one of those locales, but zu-ZA (Zulu) is instead? And the person only speaks af-ZA (Afrikaans) and English (they don't know Zulu). If we pick zu-ZA, they won't be able to understand the page's content. But if we had defaulted to English, then this would not be a problem.

If we actually knew that they accept english then some "en" locale would've already matched before this new MatchType comes into play. So this scenario can only happen if neither english nor zulu is at all part of the Accept-Language header. In which case it's pure speculation that it would be more likely that they understand english than zulu. Of course, much more people in the world speak english than zulu, however:

1. we already know that the user accepts a locale with country South Africa, so in this case the world-wide statistic of english-speakers vs. zulu-speakers wouldn't really matter, what would matter would be the statistic for South African english-speakers vs. zulu-speakers. And, if you look at https://en.wikipedia.org/wiki/Languages_of_South_Africa , it seems like zulu is a more common native language in South Africa than english (and if it isn't, doesn't matter, it's just an example). Therefore, in this random example, it would actually be better to match zu-ZA instead of en-US because the country matches better and the language also has a higher chance of fitting since it's another language of the preferred country, instead of just some random default language that the user doesn't have any direct connection to
2. the default language can just as well not be english. If I have a swedish company that creates their content in swedish before translating it to english, and an american user that for some reason has their Accept-Language only set to "es-US" visits my site, in that scenario it would clearly be better for the visitor to see "en-US" instead of the original swedish website.

**Comment by nbouvrette** [comment]
@L3444 just released version [3.1.0](https://github.com/Avansai/resolve-accept-language/releases/tag/v3.1.0), which I believe will cover your suggestion in this issue. Basically, I ended up adding 2 new match types:

1) **Language Country Match**: looks for a locale that matches the default locale's language but in a country from a locale specified in a directive. This one applies all the time and improves the previous default behavior, in my opinion. The main thinking is that the quality of the match should be similar to the default locale, but the experience might be improved because of the country-specific formats (date, currency, etc.).
2) **Country Match**: looks for a locale that matches the country in the next round of directives. This one requires the following option to be enabled: `{ matchCountry: true }`.

I updated the README explaining the new option and why it's not enabled by default.

I'm going to close this issue for now since I believe it is complete, but please let me know if you have any feedback or comments.

Thanks again for your great suggestion.
