### ISSUE TITLE
languageBased when exact local is in header

### ISSUE THREAD

**Issue by jhmen** [Avansai/resolve-accept-language#13]
Hi,

When i have the the AcceptLangauage header: `de,de-DE;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6` and then pass the locales: `['de-AT', 'de-DE']`. The local `de-AT` gets matched based on the language.

I think the package should return the exact matcht. In this case `de-DE`

What do you think about this?

If you need more information please hit me up.

**Comment by nbouvrette** [comment]
@jhmen thanks - I'll investigate as soon as possible. Could you provide the version of the package you are using and also your default locale?

**Comment by nbouvrette** [comment]
Just to keep you posted @jhmen - I am actively working on a fix... you found a very good case that was not covered and this needs to be supported.

While trying to fix the code I kind of had a few ideas to simplify the package a lot.. so I will most likely release a major feature that relies more on simple functions rather than use classes...

The fix should be out in the next few days (maybe even today)

**Comment by jhmen** [comment]
> Just to keep you posted @jhmen - I am actively working on a fix... you found a very good case that was not covered and this needs to be supported.
> 
> While trying to fix the code I kind of had a few ideas to simplify the package a lot.. so I will most likely release a major feature that relies more on simple functions rather than using classes...
> 
> The new version should be out in the next few days

Thank you for the update. If I can help you let me know.

**Comment by nbouvrette** [comment]
Thanks for the offer. The good news is that I am on vacation and have more spare time than usual 😅

I just did a major release, from which you can see all the changes here: https://github.com/Avansai/resolve-accept-language/commit/38011b33aacbd11e0043a42a54e262d033535f66

Basically, I added a new match type between the "locale-based matches" and "language-based matches," which I called "language-specific locale match." It does exactly what you suggested, and I also added tests for it. I think it's a great addition that will make matches better.

And I simplified all the APIs and code since I was at it. You can see the migration guide [here](https://github.com/Avansai/resolve-accept-language/blob/main/V2-TO-V3-UPGRADE-GUIDE.md).

Let me know what you think.

I'm going to close this issue for now - thanks again for suggesting this enhancement.

**Comment by jhmen** [comment]
> Thanks for the offer. The good news is that I am on vacation and have more spare time than usual 😅
> 
> I just did a major release, from which you can see all the changes here: [38011b3](https://github.com/Avansai/resolve-accept-language/commit/38011b33aacbd11e0043a42a54e262d033535f66)
> 
> Basically, I added a new match type between the "locale-based matches" and "language-based matches," which I called "language-specific locale match." It does exactly what you suggested, and I also added tests for it. I think it's a great addition that will make matches better.
> 
> And I simplified all the APIs and code since I was at it. You can see the migration guide [here](https://github.com/Avansai/resolve-accept-language/blob/main/V2-TO-V3-UPGRADE-GUIDE.md).
> 
> Let me know what you think.
> 
> I'm going to close this issue for now - thanks again for suggesting this enhancement.

Hi, I tested the new version, and my case works. I love the new API design. Good work, thank you. 💯
