### ISSUE TITLE
Locale "es-419" not supported

### ISSUE THREAD

**Issue by thonkinator** [Avansai/resolve-accept-language#9]
As far as I can tell, `es-419` is a valid tag, but I get an error saying `invalid locale identifier 'es-419'`.

**Comment by nbouvrette** [comment]
@thonkinator you're right it's a valid tag but what use case do you have for `es-419`? My big concern with that specific tag is that it has no date format, no currency, etc... its use case is pretty limited - typically this would be used as a translation language to save on cost but not as an actual locale on a website?

**Comment by nbouvrette** [comment]
Closing this issue due to a lack of clear use cases. @thonkinator please re-open with more details if you think this needs to be addressed

**Comment by nbouvrette** [comment]
Hi @MoSattler,

This package isn't designed to be a generic solution that supports virtually any "valid BCP47 locale." Instead, it's tailored to resolve HTTP headers limited to what popular browsers allow users to configure, while also adhering to best practices in web development.

I believe the original issue revolved around the ability to configure `es-419` as a locale used by `resolveAcceptLanguage`, demonstrated as:

`console.dir(resolveAcceptLanguage('es-419;q=0.9,fr;q=0.8', ['en-US', 'es-419', 'de-DE'], 'en-US'))`

In my opinion, no one should set their website to use `es-419` as a locale. To me, it's a "pseudo-locale" primarily utilized to cut translation costs. There isn't an `es-419` currency or date format, making it impractical for locale use. One could translate using `es-419` and then replicate their translation files to the actual locales of the countries they support.

However, there's a scenario I stumbled upon during my investigation that might pose a challenge:

`console.dir(resolveAcceptLanguage('es-419;q=0.9,fr;q=0.8', ['en-US', 'es-ES', 'de-DE'], 'en-US'))`

I'm 99% certain that when this package was developed, it wasn't possible to set `es-419` in browser settings. But it seems that's changed. Given this development, I'm open to enhancing support for such cases. For instance, in the previous example, it would return `es-ES` instead of `en-US`.

I'd appreciate your thoughts on this proposal.
